ProyectoInventarioSrn-master/src/java/sv/srn/jpa/bean/MunicipioBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.srn.jpa.bean;
import java.util.Collection;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import sv.srn.jpa.controller.MunicipioJpaController;
import sv.srn.jpa.entity.Municipio;
/**
 *
 * @author angel
 */
@ManagedBean
@SessionScoped
public class MunicipioBean {
    private EntityManagerFactory factory;
    private MunicipioJpaController controller;
    private Municipio actual = null;

    /**
     * Creates a new instance of MunicipioBean
     */
    public MunicipioBean() {
        factory = Persistence.createEntityManagerFactory("ProyectoInventarioSrnPU");
        controller = new MunicipioJpaController(factory);
    } 
       public Collection<Municipio> getItems() {
       return controller.findMunicipioEntities();
    }
       public Municipio getActual() {
       if (actual == null) {
       actual = new Municipio();
 }
 return actual;
 }
    public String crearMunicipio() throws Exception{
    Municipio MinicipioN = new Municipio();
   actual.setNombreMun(actual.getNombreMun());
   actual.setIdMunicipio(actual.getIdMunicipio());
   controller.create(actual);
   actual=null;
   return "/municipio/listado";
   
   }
    
}

ProyectoInventarioSrn-master/src/java/sv/srn/jpa/entity/Municipio.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.srn.jpa.entity;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author angel
 */
@Entity
@Table(name = "municipio")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Municipio.findAll", query = "SELECT m FROM Municipio m")
    , @NamedQuery(name = "Municipio.findByIdMunicipio", query = "SELECT m FROM Municipio m WHERE m.idMunicipio = :idMunicipio")
    , @NamedQuery(name = "Municipio.findByNombreMun", query = "SELECT m FROM Municipio m WHERE m.nombreMun = :nombreMun")})
public class Municipio implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @Column(name = "id_municipio")
    private Integer idMunicipio;
    @Basic(optional = false)
    @Column(name = "nombre_mun")
    private String nombreMun;
    @JoinColumn(name = "id_departamento", referencedColumnName = "id_departamento")
    @ManyToOne(optional = false)
    private Departamento idDepartamento;
    @OneToMany(mappedBy = "idMunicipioPrv")
    private Collection<Proveedor> proveedorCollection;

    public Municipio() {
    }

    public Municipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

    public Municipio(Integer idMunicipio, String nombreMun) {
        this.idMunicipio = idMunicipio;
        this.nombreMun = nombreMun;
    }

    public Integer getIdMunicipio() {
        return idMunicipio;
    }

    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

    public String getNombreMun() {
        return nombreMun;
    }

    public void setNombreMun(String nombreMun) {
        this.nombreMun = nombreMun;
    }

    public Departamento getIdDepartamento() {
        return idDepartamento;
    }

    public void setIdDepartamento(Departamento idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    @XmlTransient
    public Collection<Proveedor> getProveedorCollection() {
        return proveedorCollection;
    }

    public void setProveedorCollection(Collection<Proveedor> proveedorCollection) {
        this.proveedorCollection = proveedorCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idMunicipio != null ? idMunicipio.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Municipio)) {
            return false;
        }
        Municipio other = (Municipio) object;
        if ((this.idMunicipio == null && other.idMunicipio != null) || (this.idMunicipio != null && !this.idMunicipio.equals(other.idMunicipio))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "sv.srn.jpa.entity.Municipio[ idMunicipio=" + idMunicipio + " ]";
    }
    
}

ProyectoInventarioSrn-master/web/municipio/editar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

ProyectoInventarioSrn-master/web/municipio/listado.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Municipio</title>
    </h:head>
    <h:body>
        <f:view>


            <h:form>
                <h1><h:outputText value="Lista de Municipio"/></h1>
                <h:dataTable value="#{municipioBean.items}" var="item">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="IdMunicipio"/>
                        </f:facet>
                        <h:outputText value="#{item.idMunicipio}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="NombreMun"/>
                        </f:facet>
                        <h:outputText value="#{item.nombreMun}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="IdDepartamento"/>
                        </f:facet>
                        <h:outputText value="#{item.idDepartamento}"/>
                    </h:column>
                </h:dataTable>
            </h:form>


            <h:form>
                <h1><h:outputText value="Create Municipio"/></h1>
                <h:panelGrid columns="2">
                    <h:outputLabel value="IdMunicipio:" for="idMunicipio" />
                    <h:inputText id="idMunicipio" value="#{MunicipioBean.actual.idMunicipio}" title="IdMunicipio" required="true" requiredMessage="The IdMunicipio field is required."/>
                    <h:outputLabel value="NombreMun:" for="nombreMun" />
                    <h:inputText id="nombreMun" value="#{MunicipioBean.actual.nombreMun}" title="NombreMun" required="true" requiredMessage="The NombreMun field is required."/>
                    <h:outputLabel value="IdDepartamento:" for="idDepartamento" />
                    <h:selectOneMenu id="idDepartamento" value="#{MunicipioBean.actual.idDepartamento}" title="IdDepartamento" required="true" requiredMessage="The IdDepartamento field is required.">
                        <!-- TODO: update below reference to list of available items-->
                        <f:selectItems value="#{fixme}"/>
                    </h:selectOneMenu>
                    <h:commandButton value="Agregar" action="#{MunicipioBean.crearMunicipio}"/>
                </h:panelGrid>
            </h:form>

        </f:view>

    </h:body>
</html>